import { Lock, MapPin, Settings, ShoppingBag } from "lucide-react";

export const categories = [
  {
    id: "1",
    name: "Panjabi",
    slug: "panjabi",
    subcategories: [
      { name: "Eid Collection", slug: "eid-collection" },
      { name: "Casual Panjabi", slug: "casual-panjabi" },
      { name: "Semi-Long Panjabi", slug: "semi-long-panjabi" },
      { name: "White Series", slug: "white-series" },
    ],
  },
  {
    id: "2",
    name: "Luxury Panjabi",
    slug: "luxury-panjabi",
    subcategories: [
      { name: "Signature Edition", slug: "signature-edition" },
      { name: "Exclusive Silk", slug: "exclusive-silk" },
      { name: "Hand-crafted", slug: "hand-crafted" },
    ],
  },
  {
    id: "3",
    name: "Thobe",
    slug: "thobe",
    subcategories: [
      { name: "Embroidered", slug: "embroidered-thobe" },
      { name: "Classic Arab", slug: "classic-arab-thobe" },
      { name: "Modern Fit", slug: "modern-fit-thobe" },
    ],
  },
  {
    id: "4",
    name: "Shirt",
    slug: "shirt",
    subcategories: [
      { name: "Formal Shirts", slug: "formal-shirts" },
      { name: "Casual Premium", slug: "casual-premium" },
      { name: "Linen Series", slug: "linen-series" },
      { name: "Oxford Shirts", slug: "oxford-shirts" },
    ],
  },
  {
    id: "5",
    name: "T-shirt",
    slug: "t-shirt",
    subcategories: [
      { name: "Graphic Tees", slug: "graphic-tees" },
      { name: "Oversized Fit", slug: "oversized-fit" },
      { name: "Solid Premium", slug: "solid-premium" },
      { name: "Minimalist", slug: "minimalist-t-shirts" },
    ],
  },
  {
    id: "6",
    name: "Polo Shirt",
    slug: "polo-shirt",
    subcategories: [
      { name: "Classic Polo", slug: "classic-polo" },
      { name: "Textured Knit", slug: "textured-knit" },
      { name: "Sport Edition", slug: "sport-edition" },
    ],
  },
  {
    id: "7",
    name: "Pant & Trouser",
    slug: "pant-trouser",
    subcategories: [
      { name: "Premium Chinos", slug: "premium-chinos" },
      { name: "Denim Collection", slug: "denim-collection" },
      { name: "Cargo Pants", slug: "cargo-pants" },
      { name: "Comfort Trousers", slug: "comfort-trousers" },
    ],
  },
  {
    id: "8",
    name: "Attar",
    slug: "attar",
    subcategories: [
      { name: "Arabian Oud", slug: "arabian-oud" },
      { name: "Floral Notes", slug: "floral-notes" },
      { name: "Musk Series", slug: "musk-series" },
      { name: "Alcohol Free", slug: "alcohol-free" },
    ],
  },
  {
    id: "9",
    name: "Gadgets",
    slug: "gadgets",
    subcategories: [
      { name: "Smart Watches", slug: "smart-watches" },
      { name: "TWS Earbuds", slug: "tws-earbuds" },
      { name: "Accessories", slug: "tech-accessories" },
    ],
  },
  {
    id: "10",
    name: "Perfumes",
    slug: "perfumes",
    subcategories: [
      { name: "French Collection", slug: "french-perfumes" },
      { name: "Signature Scents", slug: "signature-scents" },
      { name: "Gift Sets", slug: "perfume-gift-sets" },
    ],
  },
  {
    id: "11",
    name: "Sneakers",
    slug: "sneakers",
    subcategories: [
      { name: "Casual Walking", slug: "casual-walking" },
      { name: "Sport Performance", slug: "sport-performance" },
      { name: "Lifestyle Lows", slug: "lifestyle-lows" },
    ],
  },
  {
    id: "12",
    name: "Natural Foods",
    slug: "natural-foods",
    subcategories: [
      { name: "Organic Honey", slug: "organic-honey" },
      { name: "Pure Ghee", slug: "pure-ghee" },
      { name: "Dry Fruits Mix", slug: "dry-fruits-mix" },
      { name: "Seeds & Nuts", slug: "seeds-nuts" },
    ],
  },
  {
    id: "13",
    name: "Tupi",
    slug: "tupi",
    subcategories: [
      { name: "Turkish Caps", slug: "turkish-caps" },
      { name: "Prayer Caps", slug: "prayer-caps" },
      { name: "Design Sets", slug: "design-tupi" },
    ],
  },
  {
    id: "14",
    name: "Winter",
    slug: "winter",
    subcategories: [
      { name: "Premium Hoodies", slug: "premium-hoodies" },
      { name: "Sweatshirts", slug: "sweatshirts" },
      { name: "Jackets", slug: "jackets" },
    ],
  },
  {
    id: "15",
    name: "Combo Offers",
    slug: "combo-offers",
    subcategories: [
      { name: "Lifestyle Combo", slug: "lifestyle-combo" },
      { name: "Eid Combo", slug: "eid-combo" },
    ],
  },
];

export const heroSlides = [
  {
    id: 1,
    image: "/banner/2.jpg",
    alt: "Eid Special Collection 1",
    slug: "",
  },
  {
    id: 2,
    image: "/banner/1.jpg",
    alt: "Eid Special Collection 2",
    slug: "",
  },
  {
    id: 3,
    image: "/banner/3.jpg",
    alt: "Eid Special Collection 3",
    slug: "",
  },
  {
    id: 4,
    image: "/banner/4.jpg",
    alt: "New Season 4",
    slug: "",
  },
  {
    id: 5,
    image: "/banner/5.jpg",
    alt: "New Season 5",
    slug: "",
  },
  {
    id: 6,
    image: "/banner/6.jpg",
    alt: "Avlora Wear Banner",
    slug: "",
  },
  {
    id: 7,
    image: "/banner/7.jpg",
    alt: "Avlora Wear Banner",
    slug: "",
  },
];

export const profileActions = [
  {
    name: "My Orders",
    href: "/profile/orders",
    icon: ShoppingBag,
    color: "text-blue-600",
    bg: "bg-blue-50",
  },
  {
    name: "My Addresses",
    href: "/profile/addresses",
    icon: MapPin,
    color: "text-green-600",
    bg: "bg-green-50",
  },
  {
    name: "Change Password",
    href: "/profile/password",
    icon: Lock,
    color: "text-orange-600",
    bg: "bg-orange-50",
  },
  {
    name: "Settings",
    href: "/profile/settings",
    icon: Settings,
    color: "text-gray-600",
    bg: "bg-gray-100",
    mobileOnly: true,
  },
];

export const products = [
  {
    id: "1",
    name: "As-Shabab Panjabi - 13",
    slug: "as-shabab-panjabi-13",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    image: "/template-1.jpg",
    images: ["/template-1.jpg", "/template-2.jpg", "/template-3.jpg"],
    badge: "540 Flat",
    description:
      "This is a premium quality panjabi made with the best materials. It is very comfortable to wear and looks great. It is perfect for any occasion.",
    details: [
      { name: "Brand", value: "Avlora Wear" },
      { name: "Collection", value: "As-Shabab" },
      { name: "Color", value: "Crimson Red" },
      { name: "Material", value: "Premium 100% Cotton" },
      { name: "Weight", value: "Medium Weight" },
      { name: "Wash Care", value: "Cold Machine Wash Only" },
    ],
    sizes: [
      { name: "S", inStock: true, stock: 15, sku: "AV-AS-RED-S" },
      { name: "M", inStock: true, stock: 42, sku: "AV-AS-RED-M" },
      { name: "L", inStock: true, stock: 0, sku: "AV-AS-RED-L" },
      { name: "XL", inStock: true, stock: 28, sku: "AV-AS-RED-XL" },
      { name: "XXL", inStock: true, stock: 5, sku: "AV-AS-RED-XXL" },
    ],
    colors: [
      { name: "Ruby Red", value: "#A81D23" },
      { name: "Midnight Black", value: "#1A1A1A" },
      { name: "Royal Navy", value: "#1D2B4A" },
      { name: "Emerald Green", value: "#006B3E" },
    ],
    inStock: true,
  },
  {
    id: "2",
    name: "As-Shabab Panjabi - 08",
    slug: "as-shabab-panjabi-08",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    image: "https://picsum.photos/seed/panjabi2/1000/1000",
    badge: "540 Flat",
    inStock: true,
  },
  {
    id: "3",
    name: "As-Shabab Panjabi - 19",
    slug: "as-shabab-panjabi-19",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    image: "https://picsum.photos/seed/panjabi3/1000/1000",
    badge: "540 Flat",
    inStock: true,
  },
  {
    id: "4",
    name: "As-Shabab Panjabi - 09",
    slug: "as-shabab-panjabi-09",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    image: "https://picsum.photos/seed/panjabi4/1000/1000",
    badge: "540 Flat",
    inStock: true,
  },
  {
    id: "5",
    name: "Premium Cotton T-shirt - Insafer Banglssssdsdsd...",
    slug: "premium-cotton-t-shirt-1",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt1/3000/3000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "6",
    name: "Premium Cotton T-shirt - Salahuddin Al...",
    slug: "premium-cotton-t-shirt-2",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt2/1000/1000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "7",
    name: "Premium Cotton T-shirt - 1000",
    slug: "premium-cotton-t-shirt-3",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt3/1000/1000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "8",
    name: "Premium Cotton T-shirt - Dust",
    slug: "premium-cotton-t-shirt-4",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt4/1000/1000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "9",
    name: "Luxury Panjabi - 04",
    slug: "luxury-panjabi-04",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux1/1000/1000",
    inStock: true,
  },
  {
    id: "10",
    name: "Luxury Panjabi - 10",
    slug: "luxury-panjabi-10",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux2/1000/1000",
    inStock: true,
  },
  {
    id: "11",
    name: "Luxury Panjabi - 02",
    slug: "luxury-panjabi-02",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux3/1000/1000",
    inStock: true,
  },
  {
    id: "12",
    name: "Luxury Panjabi - 09",
    slug: "luxury-panjabi-09",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux4/1000/1000",
    inStock: true,
  },
  {
    id: "13",
    name: "Luxury Panjabi - 01",
    slug: "luxury-panjabi-01",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux5/1000/1000",
    inStock: true,
  },
  {
    id: "14",
    name: "Luxury Panjabi - 23",
    slug: "luxury-panjabi-23",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux6/1000/1000",
    inStock: false,
  },
];

export const mockOrders = [
  {
    id: "BS_NUT0_0116907",
    date: "2026-01-28",
    status: "Delivered",
    total: 2450,
    paymentMethod: "Cash on delivery",
    shippingAddress:
      "Hazari Bari Jame Mosque, Bir Uttam AK Khandakar Road, Mohakhali, Dhaka - 1212",
    items: [
      {
        id: "1",
        name: "As-Shabab Panjabi - 13",
        price: 1350,
        quantity: 1,
        size: "XL",
        image: "/template-1.jpg",
      },
      {
        id: "5",
        name: "Premium Cotton T-shirt - Insafer",
        price: 440,
        quantity: 2,
        size: "M",
        image: "https://picsum.photos/seed/tshirt1/1000/1000",
      },
    ],
  },
  {
    id: "BS_NUT0_0116908",
    date: "2026-03-25",
    status: "Shipped",
    total: 1890,
    paymentMethod: "Online Payment",
    shippingAddress: "House 12, Road 5, Dhanmondi, Dhaka - 1209",
    items: [
      {
        id: "9",
        name: "Luxury Panjabi - 04",
        price: 4450,
        quantity: 1,
        size: "L",
        image: "https://picsum.photos/seed/lux1/1000/1000",
      },
    ],
  },
  {
    id: "BS_NUT0_0116909",
    date: "2026-03-26",
    status: "Processing",
    total: 1350,
    paymentMethod: "Cash on delivery",
    shippingAddress: "Plot 4, Sector 7, Uttara, Dhaka - 1230",
    items: [
      {
        id: "2",
        name: "As-Shabab Panjabi - 08",
        price: 1350,
        quantity: 1,
        size: "XXL",
        image: "https://picsum.photos/seed/panjabi2/1000/1000",
      },
    ],
  },
  {
    id: "BS_NUT0_0116910",
    date: "2026-03-27",
    status: "Pending",
    total: 880,
    paymentMethod: "Cash on delivery",
    shippingAddress: "Flat 3B, House 56, Gulshan 2, Dhaka - 1212",
    items: [
      {
        id: "6",
        name: "Premium Cotton T-shirt - Salahuddin",
        price: 440,
        quantity: 2,
        size: "L",
        image: "https://picsum.photos/seed/tshirt2/1000/1000",
      },
    ],
  },
];

export const DISTRICTS = [
  { value: 1, name: "Bagerhat", bn: "বাগেরহাট" },
  { value: 2, name: "Bandarban", bn: "বান্দরবান" },
  { value: 3, name: "Barguna", bn: "বরগুনা" },
  { value: 4, name: "Barisal", bn: "বরিশাল" },
  { value: 5, name: "Bhola", bn: "ভোলা" },
  { value: 6, name: "Bogra", bn: "বগুড়া" },
  { value: 7, name: "Brahmanbaria", bn: "ব্রাহ্মণবাড়িয়া" },
  { value: 8, name: "Chandpur", bn: "চাঁদপুর" },
  { value: 9, name: "Chapai Nawabganj", bn: "চাঁপাইনবাবগঞ্জ" },
  { value: 10, name: "Chattogram", bn: "চট্টগ্রাম" },
  { value: 11, name: "Chuadanga", bn: "চুয়াডাঙ্গা" },
  { value: 12, name: "Comilla", bn: "কুমিল্লা" },
  { value: 13, name: "Cox's Bazar", bn: "কক্সবাজার" },
  { value: 14, name: "Dhaka - City Corporation", bn: "ঢাকা" },
  {
    value: 15,
    name: "Dhaka - Outside City Corporation",
    bn: "ঢাকা সিটি কর্পোরেশনের বাইরে",
  },
  { value: 16, name: "Dinajpur", bn: "দিনাজপুর" },
  { value: 17, name: "Faridpur", bn: "ফরিদপুর" },
  { value: 18, name: "Feni", bn: "ফেনী" },
  { value: 19, name: "Gaibandha", bn: "গাইবান্ধা" },
  { value: 20, name: "Gazipur", bn: "গাজীপুর" },
  { value: 21, name: "Gopalganj", bn: "গোপালগঞ্জ" },
  { value: 22, name: "Habiganj", bn: "হবিগঞ্জ" },
  { value: 23, name: "Jamalpur", bn: "জামালপুর" },
  { value: 24, name: "Jashore", bn: "যশোর" },
  { value: 25, name: "Jhalokathi", bn: "ঝালকাঠি" },
  { value: 26, name: "Jhenaidah", bn: "ঝিনাইদহ" },
  { value: 27, name: "Joypurhat", bn: "জয়পুরহাট" },
  { value: 28, name: "Khagrachari", bn: "খাগড়াছড়ি" },
  { value: 29, name: "Khulna", bn: "খুলনা" },
  { value: 30, name: "Kishoreganj", bn: "কিশোরগঞ্জ" },
  { value: 31, name: "Kurigram", bn: "কুড়িগ্রাম" },
  { value: 32, name: "Kushtia", bn: "কুষ্টিয়া" },
  { value: 33, name: "Lakshmipur", bn: "লক্ষ্মীপুর" },
  { value: 34, name: "Lalmonirhat", bn: "লালমনিরহাট" },
  { value: 35, name: "Madaripur", bn: "মাদারীপুর" },
  { value: 36, name: "Magura", bn: "মাগুরা" },
  { value: 37, name: "Manikganj", bn: "মানিকগঞ্জ" },
  { value: 38, name: "Meherpur", bn: "মেহেরপুর" },
  { value: 39, name: "Moulvibazar", bn: "মৌলভীবাজার" },
  { value: 40, name: "Munshiganj", bn: "মুন্সীগঞ্জ" },
  { value: 41, name: "Mymensingh", bn: "ময়মনসিংহ" },
  { value: 42, name: "Naogaon", bn: "নওগাঁ" },
  { value: 43, name: "Narail", bn: "নড়াইল" },
  { value: 44, name: "Narayanganj", bn: "নারায়ণগঞ্জ" },
  { value: 45, name: "Narsingdi", bn: "নরসিংদী" },
  { value: 46, name: "Natore", bn: "নাটোর" },
  { value: 47, name: "Netrokona", bn: "নেত্রকোনা" },
  { value: 48, name: "Nilphamari", bn: "নীলফামারী" },
  { value: 49, name: "Noakhali", bn: "নোয়াখালী" },
  { value: 50, name: "Pabna", bn: "পাবনা" },
  { value: 51, name: "Panchagarh", bn: "পঞ্চগড়" },
  { value: 52, name: "Patuakhali", bn: "পটুয়াখালী" },
  { value: 53, name: "Pirojpur", bn: "পিরোজপুর" },
  { value: 54, name: "Rajbari", bn: "রাজবাড়ী" },
  { value: 55, name: "Rajshahi", bn: "রাজশাহী" },
  { value: 56, name: "Rangamati", bn: "রাঙ্গামাটি" },
  { value: 57, name: "Rangpur", bn: "রংপুর" },
  { value: 58, name: "Satkhira", bn: "সাতক্ষীরা" },
  { value: 59, name: "Shariatpur", bn: "শরীয়তপুর" },
  { value: 60, name: "Sherpur", bn: "শেরপুর" },
  { value: 61, name: "Sirajganj", bn: "সিরাজগঞ্জ" },
  { value: 62, name: "Sunamganj", bn: "সুনামগঞ্জ" },
  { value: 63, name: "Sylhet", bn: "সিলেট" },
  { value: 64, name: "Tangail", bn: "টাঙ্গাইল" },
  { value: 65, name: "Thakurgaon", bn: "ঠাকুরগাঁও" },
];
