export const categories = [
  { id: "1", name: "Panjabi", slug: "panjabi" },
  { id: "2", name: "Luxury Panjabi", slug: "luxury-panjabi" },
  { id: "3", name: "Thobe", slug: "thobe" },
  { id: "4", name: "Shirt", slug: "shirt" },
  { id: "5", name: "T-shirt", slug: "t-shirt" },
  { id: "6", name: "Polo Shirt", slug: "polo-shirt" },
  { id: "7", name: "Pant & Trouser", slug: "pant-trouser" },
  { id: "8", name: "Attar", slug: "attar" },
  { id: "9", name: "Gadgets", slug: "gadgets" },
  { id: "10", name: "Perfumes", slug: "perfumes" },
  { id: "11", name: "Sneakers", slug: "sneakers" },
  { id: "12", name: "Natural Foods", slug: "natural-foods" },
  { id: "13", name: "Tupi", slug: "tupi" },
  { id: "14", name: "Winter", slug: "winter" },
  { id: "15", name: "Combo Offers", slug: "combo-offers" },
];

export const products = [
  {
    id: "1",
    name: "As-Shabab Panjabi - 13",
    slug: "as-shabab-panjabi-13",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    // image: "https://picsum.photos/seed/panjabi1/1000/1000",
    image: "/template-1.jpg",
    images: [
      // "https://picsum.photos/seed/panjabi1/1000/1000",
      // "https://picsum.photos/seed/panjabi1-2/1000/1000",
      // "https://picsum.photos/seed/panjabi1-3/1000/1000",
      "/template-1.jpg",
      "/template-2.jpg",
      "/template-3.jpg",
    ],
    badge: "540 Flat",
    inStock: true,
  },
  {
    id: "2",
    name: "As-Shabab Panjabi - 08",
    slug: "as-shabab-panjabi-08",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    image: "https://picsum.photos/seed/panjabi2/1000/1000",
    badge: "540 Flat",
    inStock: true,
  },
  {
    id: "3",
    name: "As-Shabab Panjabi - 19",
    slug: "as-shabab-panjabi-19",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    image: "https://picsum.photos/seed/panjabi3/1000/1000",
    badge: "540 Flat",
    inStock: true,
  },
  {
    id: "4",
    name: "As-Shabab Panjabi - 09",
    slug: "as-shabab-panjabi-09",
    price: 1350,
    originalPrice: 1890,
    category: "panjabi",
    image: "https://picsum.photos/seed/panjabi4/1000/1000",
    badge: "540 Flat",
    inStock: true,
  },
  {
    id: "5",
    name: "Premium Cotton T-shirt - Insafer Bangl...",
    slug: "premium-cotton-t-shirt-1",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt1/1000/1000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "6",
    name: "Premium Cotton T-shirt - Salahuddin Al...",
    slug: "premium-cotton-t-shirt-2",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt2/1000/1000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "7",
    name: "Premium Cotton T-shirt - 1000",
    slug: "premium-cotton-t-shirt-3",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt3/1000/1000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "8",
    name: "Premium Cotton T-shirt - Dust",
    slug: "premium-cotton-t-shirt-4",
    price: 440,
    originalPrice: 550,
    category: "t-shirt",
    image: "https://picsum.photos/seed/tshirt4/1000/1000",
    badge: "20 %",
    inStock: true,
  },
  {
    id: "9",
    name: "Luxury Panjabi - 04",
    slug: "luxury-panjabi-04",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux1/1000/1000",
    inStock: true,
  },
  {
    id: "10",
    name: "Luxury Panjabi - 10",
    slug: "luxury-panjabi-10",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux2/1000/1000",
    inStock: true,
  },
  {
    id: "11",
    name: "Luxury Panjabi - 02",
    slug: "luxury-panjabi-02",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux3/1000/1000",
    inStock: true,
  },
  {
    id: "12",
    name: "Luxury Panjabi - 09",
    slug: "luxury-panjabi-09",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux4/1000/1000",
    inStock: true,
  },
  {
    id: "13",
    name: "Luxury Panjabi - 01",
    slug: "luxury-panjabi-01",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux5/1000/1000",
    inStock: true,
  },
  {
    id: "14",
    name: "Luxury Panjabi - 23",
    slug: "luxury-panjabi-23",
    price: 4450,
    category: "luxury-panjabi",
    image: "https://picsum.photos/seed/lux6/1000/1000",
    inStock: false,
  },
];
